# Site information
site_name: NEPHELE Documentation
site_url: https://github.com/TEXTaiLES/SAMplify_SuGaR
site_author: Vaia Zachari
site_description: Documentation for the NEPHELE 3D reconstruction pipeline

# Copyright
copyright: Copyright © 2025 NEPHELE

# Repository
repo_name: SAMplify_SuGaR
repo_url: https://github.com/TEXTaiLES/SAMplify_SuGaR

# Config
theme:
  name: material
  palette:
    scheme: slate
    primary: grey
  logo: assets/nephele_logo_2.png
  favicon: assets/nephele_logo_2.png

# Extra
extra:
  social: 
    - icon: fontawesome/brands/github
      link: https://github.com/TEXTaiLES/SAMplify_SuGaR

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

# Page structure
nav:
  - Deployment:
    - Installation: deployment/installation_basic.md
    - Dataset Preparation: deployment/dataset_preparation.md
    - Running the Backend Pipeline: deployment/run_pipeline.md
    - Web UI (nefele_ui): deployment/nefele_ui.md

  - Reference:
    - COLMAP – Structure-from-Motion: manual/colmap.md
    - SuGaR / PGSR: manual/sugar.md
    - Environment Variables: api/env.md

